$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    navText:false,
    nav:false,
    loop:false,
    autoplay:true,
    autoplayTimeout:3000,
    responsive:{
        0:{
            items:1,
            nav:false,
            dotsEach:2
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:3,
        }
    }
})